# Generated by Django 5.2.4 on 2025-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_notifications"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="backupcode",
            new_name="backup_code_user_id_691aaf_idx",
            old_name="backup_code_user_id_used_idx",
        ),
        migrations.RenameIndex(
            model_name="backupcode",
            new_name="backup_code_code_2a1003_idx",
            old_name="backup_code_code_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_8ab96f_idx",
            old_name="notifications_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_6b5847_idx",
            old_name="notifications_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_schedul_ce73c9_idx",
            old_name="notifications_scheduled_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_created_e4c995_idx",
            old_name="notifications_created_idx",
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "meal_type"], name="meals_user_id_90570f_idx"
            ),
        ),
    ]
