# Generated by Django 5.2.4 on 2025-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_mobile_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_sms_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Whether to receive SMS notifications",
                verbose_name="receive SMS notifications",
            ),
        ),
    ]
