# Generated by Django 5.2.4 on 2025-07-12 14:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_sms_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Sync"),
                            ("incremental", "Incremental Sync"),
                            ("upload", "Upload Only"),
                            ("download", "Download Only"),
                        ],
                        default="incremental",
                        max_length=20,
                        verbose_name="sync type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "meals_uploaded",
                    models.IntegerField(default=0, verbose_name="meals uploaded"),
                ),
                (
                    "meals_downloaded",
                    models.IntegerField(default=0, verbose_name="meals downloaded"),
                ),
                (
                    "notifications_downloaded",
                    models.IntegerField(
                        default=0, verbose_name="notifications downloaded"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="duration (seconds)"
                    ),
                ),
                (
                    "data_size_bytes",
                    models.BigIntegerField(default=0, verbose_name="data size (bytes)"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="app version"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="OS version"
                    ),
                ),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "db_table": "sync_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="devicetoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "device token",
                "verbose_name_plural": "device tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="pushnotification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "push notification",
                "verbose_name_plural": "push notifications",
            },
        ),
        migrations.RemoveIndex(
            model_name="apiusagelog",
            name="idx_api_usage_user_endpoint",
        ),
        migrations.RemoveIndex(
            model_name="apiusagelog",
            name="idx_api_usage_ip_endpoint",
        ),
        migrations.RemoveIndex(
            model_name="meal",
            name="idx_meals_user_consumed",
        ),
        migrations.RemoveIndex(
            model_name="meal",
            name="idx_meals_user_updated",
        ),
        migrations.RemoveIndex(
            model_name="mealitem",
            name="idx_meal_items_meal_food",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notifications_user_upd",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="idx_payments_user_status",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="device_toke_user_id_af4827_idx",
            old_name="idx_device_user_platform",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="device_toke_token_e218ea_idx",
            old_name="idx_device_token",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="device_toke_device__78fe17_idx",
            old_name="idx_device_device_id",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="device_toke_is_acti_df15e4_idx",
            old_name="idx_device_is_active",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_user_id_9940be_idx",
            old_name="idx_invoices_user_status",
        ),
        migrations.RenameIndex(
            model_name="pushnotification",
            new_name="push_notifi_user_id_d4b225_idx",
            old_name="idx_push_user_status",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_user_id_8d58fd_idx",
            old_name="idx_subscriptions_user_stat",
        ),
        migrations.AlterUniqueTogether(
            name="devicetoken",
            unique_together={("user", "device_id")},
        ),
        migrations.RemoveField(
            model_name="pushnotification",
            name="notification_type",
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last used at"
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="os_version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="OS version"
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="expo_receipt_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Expo receipt ID"
            ),
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="expo_ticket_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Expo ticket ID"
            ),
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="failed at"),
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="apiusagelog",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error message if the request failed",
                null=True,
                verbose_name="error message",
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="app_version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="app version"
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="device_id",
            field=models.CharField(
                help_text="Unique device identifier",
                max_length=255,
                verbose_name="device ID",
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="device_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable device name",
                max_length=255,
                null=True,
                verbose_name="device name",
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="platform",
            field=models.CharField(
                choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                max_length=20,
                verbose_name="platform",
            ),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.TextField(verbose_name="device token"),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="body",
            field=models.TextField(verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional data to send with the notification",
                verbose_name="additional data",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="delivered at"
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="device_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_notifications",
                to="api.devicetoken",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="error message"),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["stripe_invoice_id"], name="invoices_stripe__83e0c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["due_date"], name="invoices_due_dat_039a25_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["created_at"], name="invoices_created_bfa8ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_user_id_1b771c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_payment_intent_id"], name="payments_stripe__6cb0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_created_e3a130_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["user", "is_default"], name="payment_met_user_id_332e3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["stripe_payment_method_id"],
                name="payment_met_stripe__52abfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["device_token", "status"], name="push_notifi_device__376bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["created_at"], name="push_notifi_created_d308cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotification",
            index=models.Index(
                fields=["expo_receipt_id"], name="push_notifi_expo_re_9e8958_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="subscriptio_stripe__aa726e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="subscriptio_current_0ac39a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["plan_type"], name="subscriptio_plan_ty_9c7ad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active"], name="subscriptio_is_acti_4d4352_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="devicetoken",
            table="device_tokens",
        ),
        migrations.AlterModelTable(
            name="pushnotification",
            table="push_notifications",
        ),
        migrations.AddField(
            model_name="synclog",
            name="device_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="api.devicetoken",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="devicetoken",
            name="device_model",
        ),
        migrations.RemoveField(
            model_name="devicetoken",
            name="last_used",
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["user", "status"], name="sync_logs_user_id_cf7e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["started_at"], name="sync_logs_started_2c7a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["sync_type"], name="sync_logs_sync_ty_c64e53_idx"
            ),
        ),
    ]
