# Generated by Django 5.2.4 on 2025-07-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_add_performance_indexes"),
        ("api", "0015_blacklistedtoken_smsotpcode_smsratelimit_and_more"),
    ]

    operations = []
